export const SIGNUP_PENDING = 'SIGN_UP_PENDING';
export const SIGNUP_SUCCESS = 'SIGN_UP_SUCCESS';
export const SIGNUP_ERROR = 'SIGN_UP_ERROR';

export const LOGIN_PENDING = 'LOGIN_PENDING';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';

export const FETCH_CONTACTS_PENDING = 'FETCH_CONTACTS_PENDING';
export const FETCH_CONTACTS_SUCCESS = 'FETCH_CONTACTS_SUCCESS';
export const FETCH_CONTACTS_ERROR = 'FETCH_CONTACTS_ERROR';

export const FETCH_ONECONTACT_PENDING = 'FETCH_ONECONTACT_PENDING';
export const FETCH_ONECONTACT_SUCCESS = 'FETCH_ONECONTACT_SUCCESS';
export const FETCH_ONECONTACT_ERROR = 'FETCH_ONECONTACT_ERROR';


export const PUT_ONECONTACT_PENDING ='PUT_ONECONTACT_PENDING';
export const PUT_ONECONTACT_SUCCESS ='PUT_ONECONTACT_SUCCESS';
export const PUT_ONECONTACT_ERROR ='PUT_ONECONTACT_ERROR';

export const DELETE_ONECONTACT_PENDING = 'DELETE_ONECONTACT_PENDING';
export const DELETE_ONECONTACT_SUCCESS = 'DELETE_ONECONTACT_SUCCESS';
export const DELETE_ONECONTACT_ERROR = 'DELETE_ONECONTACT_ERROR';


export const ADD_NOTICE = 'ADD_NOTICE';
export const REFRESH_PAGE = 'REFRESH_PAGE';